### Use Python to query Bigquery

In [50]:
import pandas
query = """
SELECT 
    player_id, pos, firstname, lastname, birth_city, birth_state, birth_country, college_abb, exp_first_year, 
    draft_round, draft_overall_pick

FROM 
    [nba.alltime_players_profile]

WHERE 
    college_abb = "North Carolina"

ORDER BY exp_first_year DESC
"""
pandas.io.gbq.read_gbq(query, project_id='sports-1211')

Waiting for job to complete...

,player_id,pos,firstname,lastname,birth_city,birth_state,birth_country,college_abb,exp_first_year,draft_round,draft_overall_pick
0,609569,PF,James Michael,McAdoo,Norfolk,VA,United States,North Carolina,2014,NaN,NaN
1,609567,SF,P.J.,Hairston,Greensboro,NC,United States,North Carolina,2014,1,26
2,552335,SF,Reggie,Bullock,Kinston,NC,United States,North Carolina,2013,1,25
3,502871,PF,John,Henson,Greensoboro,NC,United States,North Carolina,2012,1,14
4,462461,C,Tyler,Zeller,Visalia,CA,United States,North Carolina,2012,1,17
5,552334,PG,Kendall,Marshall,Dumfries,VA,United States,North Carolina,2012,1,13
6,552336,SF,Harrison,Barnes,Ames,IA,United States,North Carolina,2012,1,7
7,462458,PF,Ed,Davis,Washington,DC,United States,North Carolina,2010,1,13
8,295923,PF,Tyler,Hansbrough,Columbia,MO,United States,North Carolina,2009,1,13
9,329672,PG,Ty,Lawson,Clinton,MD,United States,North Carolina,2009,1,18
10,329670,SG,Wayne,Ellington,Wynnewood,PA,United States,North Carolina,2009,1,28
11,295922,SG,Danny,Green,North Babylon,NY,United States,North Carolina,2009,2,46
12,76156,SG,Jawad,Williams,Cleveland,OH,United States,North Carolina,2008,NaN,NaN
13,329675,PF,Brandan,Wright,Nashville,TN,United States,North Carolina,2007,1,8
14,174069,SF,David,Noel,Durham,NC,United States,North Carolina,2006,2,39
15,263884,PF,Marvin,Williams,Bremerton,WA,United States,North Carolina,2005,1,2
16,174063,SG,Raymond,Felton,Marion,SC,United States,North Carolina,2005,1,5
17,174067,SG,Rashad,McCants,Asheville,NC,United States,North Carolina,2005,1,14
18,174066,PF,Sean,May,Chicago,IL,United States,North Carolina,2005,1,13
19,3513,C,Brendan,Haywood,New York,NY,United States,North Carolina,2001,1,20
20,3516,SG,Joseph,Forte,Atlanta,GA,United States,North Carolina,2001,1,21
21,3449,PF,Ademola,Okulaja,Lagos,,Nigeria,North Carolina,2000,NaN,NaN
22,3295,PF,Makhtar,Ndiaye,Dakar,,Senegal,North Carolina,1998,NaN,NaN
23,3229,PF,Antawn,Jamison,Shreveport,LA,United States,North Carolina,1998,1,4
24,3230,SG,Vince,Carter,Daytona Beach,FL,United States,North Carolina,1998,1,5
25,3259,PG,Shammond,Williams,Bronx,NY,United States,North Carolina,1998,2,34
26,3179,C,Serge,Zwikker,Maassluis,,Netherlands,North Carolina,1997,2,29
27,3139,C,Kevin,Salvadori,Wheeling,WV,United States,North Carolina,1996,NaN,NaN
28,3113,PG,Jeff,McInnis,Charlotte,NC,United States,North Carolina,1996,2,37
29,2987,SG,Jerry,Stackhouse,Kinston,NC,United States,North Carolina,1995,1,3
...,...,...,...,...,...,...,...,...,...,...,...
44,381,PF,Joe,Wolf,Kohler,WI,United States,North Carolina,1987,1,13
45,316,PG,Kenny,Smith,Queens,NY,United States,North Carolina,1987,1,6
46,77,C,Brad,Daugherty,Asheville,NC,United States,North Carolina,1986,1,1
47,175,SG,Michael,Jordan,Brooklyn,NY,United States,North Carolina,1984,1,3
48,261,C,Sam,Perkins,Brooklyn,NY,United States,North Carolina,1984,1,4
49,387,SF,James,Worthy,Gastonia,NC,United States,North Carolina,1982,1,1
50,1245,PF,Rich,Yonakor,Euclid,OH,United States,North Carolina,1981,3,61
51,1240,SG,Al,Wood,Gray,GA,United States,North Carolina,1981,1,4
52,1026,SG,Mike,O'Koren,Jersey City,NJ,United States,North Carolina,1980,1,6
53,540,SG,Dudley,Bradley,Baltimore,MD,United States,North Carolina,1979,1,13
54,670,PG,Phil,Ford,Rocky Mount,NC,United States,North Carolina,1978,1,2
55,610,C,Geoff,Crompton,Burlington,NC,United States,North Carolina,1978,4,70
56,891,PF,Tom,LaGarde,Detroit,MI,United States,North Carolina,1977,1,9
57,886,PG,John,Kuester,Richmond,VA,United States,North Carolina,1977,3,53
58,80,SG,Walter,Davis,Pineville,NC,United States,North Carolina,1977,1,5
59,888,PF,Mitch,Kupchak,Hicksville,NY,United States,North Carolina,1976,1,13
60,781,PF,Bobby,Jones,Charlotte,NC,United States,North Carolina,1974,1,5
61,1432,PG,Darrell,Elston,Tipton,IN,United States,North Carolina,1974,3,43
62,1555,SF,Bill,Chamberlain,,,,North Carolina,1973,3,43
63,1412,PG,George,Karl,Penn Hills,PA,United States,North Carolina,1973,4,66
64,971,PF,Bob,McAdoo,Greensboro,NC,United States,North Carolina,1972,1,2
65,1264,SG,Charlie,Scott,New York,NY,United States,North Carolina,1970,7,106
66,1965,PG,Bobby,Lewis,,,,North Carolina,1967,NaN,NaN
67,1493,PF,Billy,Cunningham,Brooklyn,NY,United States,North Carolina,1965,NaN,NaN
68,1742,SG,York,Larese,New York,NY,United States,North Carolina,1961,NaN,NaN
69,1822,SF,Lee,Shaffer,Chicago,IL,United States,North Carolina,1961,NaN,NaN
70,1623,SF,Pete,Brennan,Brooklyn,NY,United States,North Carolina,1958,NaN,NaN
71,1730,PG,Tommy,Kearns,New York,NY,United States,North Carolina,1958,NaN,NaN
72,1808,SF,Lennie,Rosenbluth,New York,NY,United States,North Carolina,1957,NaN,NaN
73,2168,SF,Hooks,Dillon,Savannah,GA,United States,North Carolina,1949,NaN,NaN